on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Step 3: Install required Python packages (without requirements.txt)
      - name: Install dependencies
        run: |
          pip install west packaging

      # Step 4: Set up the ZMK environment
      - name: Initialize ZMK environment
        run: |
          west init -l app/
          west update
          west zephyr-export

      # Step 5: Build firmware
      - name: Build firmware
        run: |
          west build -p auto -b your_board_name -- your_build_options
